"""
Export a trained TQC actor to a C header for on-chip ESP32 inference.

The observation dimension is read from the checkpoint (6 for the level rig, 8 for the tilt rig).
The generated NumPy/C-equivalent forward pass is checked against deterministic SB3 inference
before any header is written.
"""
from __future__ import annotations

import argparse
import hashlib
import os

import numpy as np
from sb3_contrib import TQC

HERE = os.path.dirname(__file__)


def _linear_params(state_dict, prefix):
    """Return a linear layer from either SB3's Linear or legacy Sequential layout."""
    for weight_key, bias_key in (
        (f"{prefix}.weight", f"{prefix}.bias"),
        (f"{prefix}.0.weight", f"{prefix}.0.bias"),
    ):
        if weight_key in state_dict and bias_key in state_dict:
            return state_dict[weight_key], state_dict[bias_key]
    keys = ", ".join(sorted(k for k in state_dict if k.startswith(prefix)))
    raise KeyError(f"cannot find actor layer {prefix!r}; matching checkpoint keys: {keys or 'none'}")


def _sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True, help="Exact SB3 .zip checkpoint to export")
    ap.add_argument("--out", default=os.path.join(HERE, "policy_weights.h"))
    args = ap.parse_args()

    m = TQC.load(args.model, device="cpu")   # compare on CPU: the ESP32 runs the float32 CPU path
    sd = {k: v.cpu().numpy() for k, v in m.policy.actor.state_dict().items()}
    W0, b0 = _linear_params(sd, "latent_pi.0")
    W1, b1 = _linear_params(sd, "latent_pi.2")
    Wm, bm = _linear_params(sd, "mu")
    H0, H1, OBS = W0.shape[0], W1.shape[0], W0.shape[1]   # OBS auto-detected (6 level, 8 with tilt)
    if OBS not in (6, 8):
        raise ValueError(f"unsupported observation dimension {OBS}; expected the 6-D or 8-D policy")
    if W1.shape[1] != H0 or Wm.shape != (1, H1):
        raise ValueError(
            f"unsupported actor shapes: W0={W0.shape}, W1={W1.shape}, Wm={Wm.shape}"
        )
    # SB3 stores clip_mean=2 even on non-gSDE actors, but only the gSDE Sequential layout actually
    # includes the Hardtanh clamp. Applying the attribute unconditionally changes deterministic
    # actions by as much as tanh(2)-tanh(large_mu) ~= -0.036.
    has_mean_clamp = "mu.0.weight" in sd
    CLIP = float(getattr(m.policy.actor, "clip_mean", 0.0)) if has_mean_clamp else 0.0

    def fwd(o):
        h = np.maximum(0.0, W0 @ o + b0)
        h = np.maximum(0.0, W1 @ h + b1)
        mu = Wm @ h + bm
        if CLIP > 0:
            mu = np.clip(mu, -CLIP, CLIP)
        return np.tanh(mu)

    # verify against SB3 on random + realistic obs
    rng = np.random.default_rng(0)
    err = 0.0
    for _ in range(200):
        o = rng.standard_normal(OBS).astype(np.float32)
        err = max(err, abs(float(fwd(o)[0]) - float(m.predict(o, deterministic=True)[0][0])))
    print(f"max |numpy_fwd - sb3.predict| = {err:.2e}  (must be tiny)")
    assert err < 1e-4, "forward mismatch -- do not deploy"

    def carr(name, a):
        flat = ", ".join(f"{x:.8e}f" for x in a.reshape(-1))
        return f"static const float {name}[{a.size}] = {{{flat}}};\n"

    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("// AUTO-GENERATED by rl/export_policy.py -- do not edit by hand.\n")
        f.write(f"// source: {args.model}\n")
        f.write(f"// source sha256: {_sha256(args.model)}\n")
        f.write(f"// actor: obs[{OBS}] -> H0 (relu) -> H1 (relu) -> 1 -> tanh ; V = 6*action\n")
        obs_fields = "cos th, sin th, thd/15, clip(phi/pi,+-2), phid/25, prev_action"
        if OBS == 8:
            obs_fields += ", beta/0.6, betad/3"
        f.write(f"// obs = [{obs_fields}]\n\n")
        f.write("#pragma once\n")
        f.write(f"#define RL_OBS {OBS}\n")
        f.write(f"#define RL_H0 {H0}\n#define RL_H1 {H1}\n")
        f.write(f"#define RL_CLIP_MEAN {CLIP:.1f}f   // gSDE mean clamp: action=tanh(clip(mu,-c,c))\n\n")
        f.write(carr("RL_W0", W0))   # (H0,OBS) row-major
        f.write(carr("RL_B0", b0))
        f.write(carr("RL_W1", W1))   # (H1,H0)
        f.write(carr("RL_B1", b1))
        f.write(carr("RL_WM", Wm))   # (1,H1)
        f.write(carr("RL_BM", bm))
    print(f"wrote {args.out}  ({W0.size+b0.size+W1.size+b1.size+Wm.size+bm.size} floats, OBS={OBS})")
    o0 = np.zeros(OBS, np.float32); o0[0] = 1.0   # cos(theta)=1 (upright), rest 0
    print("sample: predict(upright) =", float(fwd(o0)[0]))


if __name__ == "__main__":
    main()
