"""
export_policy.py — export the trained TQC actor to a C header for on-chip (ESP32) inference.

The deterministic policy is a tiny MLP:  obs[6] -> 64 (ReLU) -> 64 (ReLU) -> 1 -> tanh -> action.
Action in [-1,1] -> voltage = 6*action. Obs MUST be built on-chip exactly as in furuta_env.py:
    [cos(theta), sin(theta), theta_dot/15, clip(phi/pi,-2,2), phi_dot/25, prev_action]

Writes rl/policy_weights.h (row-major float arrays) and verifies the pure-C-equivalent numpy
forward matches SB3's predict() to <1e-5 before writing.

    python rl/export_policy.py [--model rl/models/fix_sde/best_model.zip]
"""
from __future__ import annotations

import argparse
import os

import numpy as np
from sb3_contrib import TQC

HERE = os.path.dirname(__file__)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=os.path.join(HERE, "models/fix_sde/best_model.zip"))
    ap.add_argument("--out", default=os.path.join(HERE, "policy_weights.h"))
    args = ap.parse_args()

    m = TQC.load(args.model, device="cpu")   # compare on CPU: the ESP32 runs the float32 CPU path
    sd = {k: v.cpu().numpy() for k, v in m.policy.actor.state_dict().items()}
    W0, b0 = sd["latent_pi.0.weight"], sd["latent_pi.0.bias"]   # (64,6) (64,)
    W1, b1 = sd["latent_pi.2.weight"], sd["latent_pi.2.bias"]   # (64,64)(64,)
    Wm, bm = sd["mu.0.weight"], sd["mu.0.bias"]                 # (1,64) (1,)
    H0, H1 = W0.shape[0], W1.shape[0]
    # gSDE clamps the mean: action = tanh(clip(mu, -clip_mean, +clip_mean)). MUST replicate.
    CLIP = float(getattr(m.policy.actor, "clip_mean", 0.0))

    def fwd(o):
        h = np.maximum(0.0, W0 @ o + b0)
        h = np.maximum(0.0, W1 @ h + b1)
        mu = Wm @ h + bm
        if CLIP > 0:
            mu = np.clip(mu, -CLIP, CLIP)
        return np.tanh(mu)

    # verify against SB3 on random + realistic obs
    rng = np.random.default_rng(0)
    err = 0.0
    for _ in range(200):
        o = rng.standard_normal(6).astype(np.float32)
        err = max(err, abs(float(fwd(o)[0]) - float(m.predict(o, deterministic=True)[0][0])))
    print(f"max |numpy_fwd - sb3.predict| = {err:.2e}  (must be tiny)")
    assert err < 1e-4, "forward mismatch -- do not deploy"

    def carr(name, a):
        flat = ", ".join(f"{x:.8e}f" for x in a.reshape(-1))
        return f"static const float {name}[{a.size}] = {{{flat}}};\n"

    with open(args.out, "w") as f:
        f.write("// AUTO-GENERATED by rl/export_policy.py -- do not edit by hand.\n")
        f.write(f"// source: {os.path.basename(args.model)}\n")
        f.write("// actor: obs[6] -> H0 (relu) -> H1 (relu) -> 1 -> tanh ; V = 6*action\n")
        f.write("// obs = [cos(th), sin(th), thd/15, clip(phi/pi,-2,2), phid/25, prev_action]\n\n")
        f.write("#pragma once\n")
        f.write("#define RL_OBS 6\n")
        f.write(f"#define RL_H0 {H0}\n#define RL_H1 {H1}\n")
        f.write(f"#define RL_CLIP_MEAN {CLIP:.1f}f   // gSDE mean clamp: action=tanh(clip(mu,-c,c))\n\n")
        f.write(carr("RL_W0", W0))   # (H0,6) row-major
        f.write(carr("RL_B0", b0))
        f.write(carr("RL_W1", W1))   # (H1,H0)
        f.write(carr("RL_B1", b1))
        f.write(carr("RL_WM", Wm))   # (1,H1)
        f.write(carr("RL_BM", bm))
    print(f"wrote {args.out}  ({W0.size+b0.size+W1.size+b1.size+Wm.size+bm.size} floats)")
    print("sample: predict([1,0,0,0,0,0]) =", float(fwd(np.array([1,0,0,0,0,0],np.float32))[0]))


if __name__ == "__main__":
    main()
